# Generated by Django 2.0.5 on 2018-12-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Introduce una descripcion del libro.', max_length=1000),
        ),
    ]
